name: Run Streamlit Tasks

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-app:
    runs-on: ubuntu-latest

    env:
      APPIDKEY: ${{ secrets.APPIDKEY }}  # Your secret

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit Script
        run: |
          python shop.py  # or any script that uses the secret
