name: Streamlit NSE Dashboard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-dashboard:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    env:
      APPIDKEY: ${{ secrets.APPIDKEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit App
        run: |
          streamlit run shop.py
